# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a159dd595b76a0fcfc91da36ce40b0b24c20b1119c06dccd0a4ca12b6b71b6d76c591da9196d94ea77ab3011b6d89cc4a0900da4a8c8a76c9436020e062f4400

test:
  secret_key_base: ef5659bd840bb8f09d3eb236a9b6661dd6f15171c706a90caf1b34b4b2d4c9cc7231bbd809b1d905f12e92f4899b5d06fa412d355cfdc8ebf43ecb5d9de2ee8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
